// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGiOws7CcxVxTgZeuPpYY-ZOki92jW438',
    appId: '1:1085282893101:web:e74eb4f2042eaa800da7a4',
    messagingSenderId: '1085282893101',
    projectId: 'fitx-flutter-x',
    authDomain: 'fitx-flutter-x.firebaseapp.com',
    storageBucket: 'fitx-flutter-x.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3LywM8Hil0KB59KmnZRtTmRMZ4q5l6HE',
    appId: '1:1085282893101:android:766db5861bec3d2a0da7a4',
    messagingSenderId: '1085282893101',
    projectId: 'fitx-flutter-x',
    storageBucket: 'fitx-flutter-x.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAhipWMzt3Z4UrHJLR3jRhe0AlTIhn6LA',
    appId: '1:1085282893101:ios:975d66a0150fb2e20da7a4',
    messagingSenderId: '1085282893101',
    projectId: 'fitx-flutter-x',
    storageBucket: 'fitx-flutter-x.appspot.com',
    iosClientId: '1085282893101-83csrbqsvdmopqs055k6lcsip6ajrqdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitxFlutter2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAhipWMzt3Z4UrHJLR3jRhe0AlTIhn6LA',
    appId: '1:1085282893101:ios:975d66a0150fb2e20da7a4',
    messagingSenderId: '1085282893101',
    projectId: 'fitx-flutter-x',
    storageBucket: 'fitx-flutter-x.appspot.com',
    iosClientId: '1085282893101-83csrbqsvdmopqs055k6lcsip6ajrqdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitxFlutter2',
  );
}
